In [3]:
# Import NumPy package to load its functions (np is conventional abbreviation to use in the code)
import numpy as np

In [36]:
# Initializing NumPy arrays with lists
a = np.array([1, 2, 3, 4])		# (1D) vector array (lowercase name)
A = np.array([[2, 3],   		# (2D) matrix array (uppercase name)
              [4, 5]])

# Initializing NumPy arrays with numbers
b = np.arange(5)		        # vector from 0 to 4
c = np.arange(10, 15)	        # vector from 10 to 14
d = np.arange(15, 50, 10)	    # vector from 15 to 49, with steps of 10
e = np.linspace(0, 100, 5)	    # vector 5 number values between 0 and 100
f = np.empty(2)		            # vector declaration that needs to be initialized
B = np.zeros((2, 3, 4))	        # matrix 2x3x4 (3D) matrix with zeros
C = np.ones((1, 2))		        # matrix 1x2 (2D) matrix with ones
X = np.random.rand(5, 5)	    # matrix 5x5 (2D) with random values <0, 1)
Y = np.random.randn(100, 36, 36)# matrix 50x36x36 (3D) with random numbers from normal distribution

In [37]:
print("a =", a); print("A:\n", A); print("b =", b); print("c =", c); print("d =", d); print("e =", e); 
print("f =", f); print("B:\n", B); print("C:\n", C); print("X:\n", X); print("Y:\n", Y)

a = [1 2 3 4]
A:
 [[2 3]
 [4 5]]
b = [0 1 2 3 4]
c = [10 11 12 13 14]
d = [15 25 35 45]
e = [  0.  25.  50.  75. 100.]
f = [2.91184574e-14 5.08182580e-66]
B:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
C:
 [[1. 1.]]
X:
 [[0.75366737 0.49881085 0.08654389 0.41575646 0.94460381]
 [0.95251509 0.86483616 0.64835694 0.1824719  0.15286954]
 [0.36111567 0.16050151 0.17204196 0.27152655 0.47624862]
 [0.42078317 0.1334147  0.29894496 0.4485635  0.64169186]
 [0.0667609  0.75067684 0.04064287 0.30524118 0.08582638]]
Y:
 [[[ 0.56886131  0.43748164 -0.72104155 ... -1.20277462 -1.14176569
   -0.08518875]
  [ 0.087108    0.19815367 -0.34212991 ... -0.10386498  0.51809341
    1.39947547]
  [-0.56498325 -2.05611084 -0.6853519  ...  1.02026657 -0.17496698
    0.36496658]
  ...
  [-0.91822833 -1.72474642 -1.40823634 ... -0.4297296   0.37525342
    1.44901006]
  [-0.23541697 -0.12706423  0.36044692 ...  0.07766336 -0.85922143
   -0.5273989 ]
  [ 0.7

In [38]:
# Displaying properties of NumPy arrays (shape, ndim, size)
B = np.zeros((2, 3, 4))
B_shape = B.shape   # length of each dimensions - shape of array
B_ndim = B.ndim    	# amount of array dimensions
B_size = B.size    	# amount of values in array

In [39]:
print("B_shape =", B_shape); print("B_ndim =", B_ndim); print("B_size =", B_size)

B_shape = (2, 3, 4)
B_ndim = 3
B_size = 24


In [40]:
# Transforming functions of NumPy arrays (transpose, reshape)
Y = np.random.randn(2, 2, 3)
Y_transposed = np.transpose(Y)          # transposes Y - reverses the axes of an array
Y_transposed = Y.transpose()            # does the same, without having to access np
Y_reshaped = np.reshape(Y, (2, 2 * 3))  # reshapes dimensions from 2x3x2 matrix to 2x6 
Y_reshaped = Y.reshape(2, 2 * 3)        # does the same, without having to access np
Y_reshaped = Y.reshape(-1, 2 * 3)       # does the same, -1 lets NumPy calculate the shape length based on the remaining number of elements

In [41]:
print("Y.shape =", Y.shape); print("Y:\n", Y); print("Y_transposed.shape", Y_transposed.shape); print("Y_transposed:\n", Y_transposed); 
print("Y_reshaped.shape", Y_reshaped.shape); print("Y_reshaped:\n", Y_reshaped)

Y.shape = (2, 2, 3)
Y:
 [[[ 0.57324478 -0.22017291  0.87544821]
  [ 1.17262222  0.37475888 -0.14709959]]

 [[-0.15351335  0.25644018 -0.0416597 ]
  [ 0.9422955  -0.51412511  0.02765335]]]
Y_transposed.shape (3, 2, 2)
Y_transposed:
 [[[ 0.57324478 -0.15351335]
  [ 1.17262222  0.9422955 ]]

 [[-0.22017291  0.25644018]
  [ 0.37475888 -0.51412511]]

 [[ 0.87544821 -0.0416597 ]
  [-0.14709959  0.02765335]]]
Y_reshaped.shape (2, 6)
Y_reshaped:
 [[ 0.57324478 -0.22017291  0.87544821  1.17262222  0.37475888 -0.14709959]
 [-0.15351335  0.25644018 -0.0416597   0.9422955  -0.51412511  0.02765335]]


In [42]:
# Computing functions over axises in NumPy arrays (sum/mean/exp etc.)
X = np.array([[1, 3, 5, 7],
              [6, 7, 3, 1],
              [1, 4, 5, 1]])
X_sum = np.sum(X, axis=0)	    # sum out of elements inside of 1. array: (1,6,1)(3,7,4)(5,3,5)(7,1,1) [columns]

Z = np.array([[[2, 4, 6],
               [1, 2, 3]],

              [[4, 6, 8],
               [7, 8, 9]]])
Z_mean_0 = np.mean(Z, axis=0)	# compute means out of elements inside of 1. array - 1. row uses: (2,4)(4,6)(6,8)  [1on1 outside]
Z_mean_1 = np.mean(Z, axis=1)	# compute means out of elements inside of 2. array - 1. row uses: (2,1)(4,2),(6,3) [columns]
Z_mean_2 = Z.mean(axis=2)	    # compute means out of elements inside of 3. array - 1. row uses: (2,4,6)(1,2,3)   [rows]

In [43]:
print("X_sum", X_sum); print("Z_mean_0:\n", Z_mean_0)
print("Z_mean_1:\n", Z_mean_1); print("Z_mean_2:\n", Z_mean_2)

X_sum [ 8 14 13  9]
Z_mean_0:
 [[3. 5. 7.]
 [4. 5. 6.]]
Z_mean_1:
 [[1.5 3.  4.5]
 [5.5 7.  8.5]]
Z_mean_2:
 [[4. 2.]
 [6. 8.]]


In [44]:
# Arithmetic element wise operations with vectors
a1 = np.array([9, 8, 7, 6])
a2 = np.array([1, 2, 3, 4])
a_added = a1 + a2   # adding (np.add - has more parameters for adding)
a_subtr = a1 - a2   # subtracting (np.subtract)
a_multi = a1 * a2   # multiplication (np.multiply)
a_divid = a1 / a2   # division (np.divide)

# Vectorization with np. vs Python loops)
# ELEMENT WISE MULTIPLICATION
a_multi = np.multiply(a1,a2)    # [9*1, 8*2, 7*3, 8*4]
a_multi = np.zeros(len(a1))
for i in range(len(a1)):
    a_multi[i] = a1[i] * a2[i]

# DOT PRODUCT
a_dot = np.dot(a1,a2)	        # 9*1 + 8*2 + 7*3 + 6*4
a_dot = 0
for i in range(len(a1)):
    a_dot += a1[i] * a2[i]

# OUTER PRODUCT
a_outer = np.outer(a1,a2)	    # [[9*1, 9*2, 9*3, 9*4], [8*1, 8*2 …], … ]
a_outer = np.zeros((len(a1),len(a2)))
for i in range(len(a1)):
    for j in range(len(a2)):
        a_outer[i,j] = a1[i] * a2[j]

In [45]:
print("a_added =", a_added); print("a_subtr =", a_subtr); print("a_multi =", a_multi); print("a_divid =", a_divid);
print("a_multi =", a_multi); print("a_dot =", a_dot); print("a_outer:\n", a_outer)

a_added = [10 10 10 10]
a_subtr = [8 6 4 2]
a_multi = [ 9. 16. 21. 24.]
a_divid = [9.         4.         2.33333333 1.5       ]
a_multi = [ 9. 16. 21. 24.]
a_dot = 70
a_outer:
 [[ 9. 18. 27. 36.]
 [ 8. 16. 24. 32.]
 [ 7. 14. 21. 28.]
 [ 6. 12. 18. 24.]]


In [46]:
# Arithmetic operations with matrix and vector (multiplication and dot product)
a1 = np.array([1, 2, 3, 4])
A1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])

Aa_multi = np.multiply(A1, a1)  # [[1*1, 2*2, 3*3, 4*4], [1*5, 1*6, 1*7, 1*8]]
Aa_dot = np.dot(A1, a1)         # [1*1 + 2*2 + 3*3 + 4*4, 5*1 + 6*2 + 7*3 + 8*4]
Aa_dot = np.zeros(A1.shape[0])
for i in range(len(A1)):
    for j in range(len(a1)):
        Aa_dot[i] += A1[i,j] * a1[j]

# Arithmetic operations with matrices (multiplication and dot product)
A2 = np.array([[4, 6],
               [3, 5],
               [2, 4],
               [1, 3]])
A11_multi = np.multiply(A1, A2.T)   # we need to transpose A2 to match the array shapes 
                                    # [[1*4, 2*3, 3*2, 4*1], [5*6, 6*5, 7*4, 8*3]]
A12_dot = np.dot(A1, A2)            # multiplying AxB * BxC shaped matrices (4x3 * 3x1) 
                                    # [[1*4 + 2*3 + 3*2 + 4*1, 1*6 + 2*5 + 3*4 + 4*3],
                                    #  [5*4 + 6*3 + 7*2 + 8*1, 5*6 + 6*5 + 7*4 + 8*3]]

In [47]:
print("Aa_multi:\n", Aa_multi); print("Aa_dot =", Aa_dot); 
print("A11_multi:\n", A11_multi); print("A12_dot:\n", A12_dot);

Aa_multi:
 [[ 1  4  9 16]
 [ 5 12 21 32]]
Aa_dot = [30. 70.]
A11_multi:
 [[ 4  6  6  4]
 [30 30 28 24]]
A12_dot:
 [[ 20  40]
 [ 60 112]]


In [48]:
# Index referencing (getting element or sublist of elements from the array)
a = np.array([1, 2, 3, 4, 5])
one = a[0]          # gets the 1. element from the vector
three = a[2]        # gets the 3. element from the vector

A = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
row_0 = A[0]        # gets 1. row from 2D matrix
eight = A[2][1]     # gets number 8 from 2D matrix
eight = A[2, 1]     # does the same

idx = [0, 2]        # saving vector as index reference in a variable
A_idxed = A[idx]    # gets first and last row from 2D matrix

# Slicing
a_sub = a[1:4]       # gets all elements except for the first and last one
a_sub = a[1:-1]      # does the same, -1 is the last element
A_sub = A[0:2]       # gets first two rows from 2D matrix
A_sub = A[:2]        # does the same
A_sub_rows = A[1:4]  # gets last two rows
A_sub_cols = A[:, 1] # gets all rows' second element

B = np.array([[[1,2,3], [2,3,4], [4,5,6]],
              [[2,3,4], [6,5,4], [4,3,2]]])
B_sub_step = B[::, ::, ::2] # gets first and last element in the vectors


In [50]:
print("one =", one); print("three =", three); print("row_0 =", row_0); print("eight =", eight)
print("a_sub =", a_sub); print("A_sub:\n", A_sub); print("A_sub_rows:\n", A_sub_rows); print("A_sub_cols =", A_sub_cols)
print("B_sub_step:\n", B_sub_step)

one = 1
three = 3
row_0 = [1 2 3]
eight = 8
a_sub = [2 3 4]
A_sub:
 [[1 2 3]
 [4 5 6]]
A_sub_rows:
 [[4 5 6]
 [7 8 9]]
A_sub_cols = [2 5 8]
B_sub_step:
 [[[1 3]
  [2 4]
  [4 6]]

 [[2 4]
  [6 4]
  [4 2]]]


In [23]:
# Copying and Broadcasting (treating arrays with different shapes during arithmetic operations)
X1 = np.array([[2, 3, 4],
               [3, 5, 8],
               [9, 8, 0]])
X2 = np.copy(X1)
X2[:] = 1   # sets all values to 1

X3 = X2.copy()
X3[0] = 0   # sets all values in the first row to 0

X4 = X3 * 2 # multipling matrix with a scalar (Python list would just duplicate the values)

In [51]:
print("X1:\n", X1); print("X2:\n", X2); print("X3:\n", X3); print("X4:\n", X4)

X1:
 [[2 3 4]
 [3 5 8]
 [9 8 0]]
X2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
X3:
 [[0 0 0]
 [1 1 1]
 [1 1 1]]
X4:
 [[0 0 0]
 [2 2 2]
 [2 2 2]]


In [6]:
# Types and conversions
# NumPy arrays contain only one type of variables. If there are more, it will be converted into string.
# If there are numbers and there’s also bool value, it’s going to be changed into a number. 
# Priorities: string > int > bool
A1 = np.zeros((3, 3))

A2 = A1.copy()
A2 = A2.astype('bool')  # conversion into bool type

A3 = A2.copy()
A3[0, 2] = True
A3[1][0] = True
A3[2] = True

# print(bool_idx.dtype)			    # float64 displays type of array
# print(bool_idx)

# X[bool_idx] = 300	# using fully sized matrix as index reference (broadcast)
# print(X)		    # [[ 0 0 300]\n [ 300 5 8]\n [ 300 300 300]]

# # Conditioned filtering
# bool_idx = X < 10	# get all 0 values
# print(bool_idx)    	# [[True True False]\n [False True True]\n [False False False]]
# X[bool_idx] = 1	    # set them to 1
# print(X)		    # [[ 1 1 300]\n [ 300 1 1]\n [ 300 300 300]]

# C = np.array([[[1,2,3],[2,3,4],[4,5,6]],
#               [[2,3,4],[6,5,4],[4,3,2]]])


In [7]:
print(A1)
print(A2)
print(A3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[False False False]
 [False False False]
 [False False False]]
[[False False  True]
 [ True False False]
 [ True  True  True]]


In [ ]:
# Stacking

a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
v_stack = np.vstack((a1, a2))	# joins arrays vertically, with a1 on the top
h_stack = np.hstack((a1, a2))	# joins arrays horizontally, with a1 on the left
print(h_stack)	# [[1 1 3 3]
#  [2 2 4 4]]

# hsplit - splits an array into several smaller arrays



Solving linear systems
A = np.array([-1, 3],
             [3, 2]])
b = np.array([7, 1])
x = np.linalg.solve(A, b)	# [-1. 2.]
d = np.linalg.det(A)	# -11