In [46]:
# Import NumPy package to load its functions (np is conventional abbreviation to use in the code)
import numpy as np

In [47]:
# Initializing NumPy arrays with lists
a = np.array([1, 2, 3, 4])      # (1D) vector array (lowercase name)
A = np.array([[2, 3],           # (2D) matrix array (uppercase name)
              [4, 5]])

# Initializing NumPy arrays with numbers
b = np.arange(5)                # vector from 0 to 4
c = np.arange(10, 15)           # vector from 10 to 14
d = np.arange(15, 50, 10)       # vector from 15 to 49, with steps of 10
e = np.linspace(0, 100, 5)      # vector 5 number values between 0 and 100
f = np.empty(2)                 # vector declaration that needs to be initialized
B = np.zeros((2, 3, 4))         # matrix 2x3x4 (3D) matrix with zeros
C = np.ones((1, 2))             # matrix 1x2 (2D) matrix with ones
X = np.random.rand(5, 5)        # matrix 5x5 (2D) with random values <0, 1) {also possible with .random_sample((5, 5))}
Y = np.random.randn(50, 36, 36)# matrix 50x36x36 (3D) with random numbers from normal distribution

In [48]:
print("a =", a); print("A:\n", A); print("b =", b);     print("c =", c); print("d =", d); print("e =", e); 
print("f =", f); print("B:\n", B); print("C:\n", C);    print("X:\n", X)

a = [1 2 3 4]
A:
 [[2 3]
 [4 5]]
b = [0 1 2 3 4]
c = [10 11 12 13 14]
d = [15 25 35 45]
e = [  0.  25.  50.  75. 100.]
f = [5.30498948e-313 9.54898106e-313]
B:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
C:
 [[1. 1.]]
X:
 [[0.4951218  0.02930821 0.9346689  0.28854498 0.09890955]
 [0.45338845 0.00691315 0.26326749 0.22502623 0.10560626]
 [0.65480493 0.88727677 0.70942118 0.82748775 0.80757582]
 [0.64608409 0.4616427  0.55639128 0.174676   0.15252499]
 [0.46125539 0.90640868 0.73158463 0.92630395 0.02199096]]


In [49]:
# Displaying properties of NumPy arrays (shape, ndim, size)
B = np.zeros((2, 3, 4))
B_shape = B.shape   # length of each dimensions - shape of array
B_ndim = B.ndim     # amount of array dimensions
B_size = B.size     # amount of values in array

In [50]:
print("B_shape =", B_shape); print("B_ndim =", B_ndim); print("B_size =", B_size)

B_shape = (2, 3, 4)
B_ndim = 3
B_size = 24


In [51]:
# Transforming functions of NumPy arrays (transpose, reshape)
Y = np.random.randn(2, 2, 3)
Y_transposed = np.transpose(Y)          # transposes Y - reverses the axes of an array
Y_transposed = Y.transpose()            # does the same, anytime we use np. with matrix parameters, it can also call it from the first matrix passed
Y_reshaped = np.reshape(Y, (2, 2 * 3))  # reshapes dimensions from 2x3x2 matrix to 2x6 
Y_reshaped = Y.reshape(-1, 2 * 3)       # does the same, -1 lets NumPy calculate the shape length based on the remaining number of elements

In [52]:
print("Y.shape =", Y.shape);                    print("Y:\n", Y); 
print("Y_transposed.shape", Y_transposed.shape);print("Y_transposed:\n", Y_transposed); 
print("Y_reshaped.shape", Y_reshaped.shape);    print("Y_reshaped:\n", Y_reshaped)

Y.shape = (2, 2, 3)
Y:
 [[[-0.57570653  1.64681495 -2.26749139]
  [ 0.51359091  2.30085699 -0.84592756]]

 [[-0.87525782 -1.37403397 -0.66549838]
  [-1.56612912 -1.39165741 -0.63969973]]]
Y_transposed.shape (3, 2, 2)
Y_transposed:
 [[[-0.57570653 -0.87525782]
  [ 0.51359091 -1.56612912]]

 [[ 1.64681495 -1.37403397]
  [ 2.30085699 -1.39165741]]

 [[-2.26749139 -0.66549838]
  [-0.84592756 -0.63969973]]]
Y_reshaped.shape (2, 6)
Y_reshaped:
 [[-0.57570653  1.64681495 -2.26749139  0.51359091  2.30085699 -0.84592756]
 [-0.87525782 -1.37403397 -0.66549838 -1.56612912 -1.39165741 -0.63969973]]


In [19]:
# Computing functions over axises in NumPy arrays (sum/mean/exp etc.)
X = np.array([[1, 3, 5, 7],
              [6, 7, 3, 1],
              [1, 4, 5, 1]])
X_sum = np.sum(X, axis=0)       # sum out of elements inside of 1. array: (1,6,1)(3,7,4)(5,3,5)(7,1,1) [columns]

Z = np.array([[[2, 4, 6],
               [1, 2, 3]],

              [[4, 6, 8],
               [7, 8, 9]]])
Z_mean_0 = np.mean(Z, axis=0)   # compute means out of elements inside of 1. array - 1. row uses: (2,4)(4,6)(6,8)  [1on1 outside]
Z_mean_1 = np.mean(Z, axis=1)   # compute means out of elements inside of 2. array - 1. row uses: (2,1)(4,2),(6,3) [columns]
Z_mean_2 = Z.mean(axis=2)       # compute means out of elements inside of 3. array - 1. row uses: (2,4,6)(1,2,3)   [rows]

In [20]:
print("X_sum", X_sum);          print("Z_mean_0:\n", Z_mean_0)
print("Z_mean_1:\n", Z_mean_1); print("Z_mean_2:\n", Z_mean_2)

X_sum [ 8 14 13  9]
Z_mean_0:
 [[3. 5. 7.]
 [4. 5. 6.]]
Z_mean_1:
 [[1.5 3.  4.5]
 [5.5 7.  8.5]]
Z_mean_2:
 [[4. 2.]
 [6. 8.]]


In [21]:
# Arithmetic element wise operations with vectors
a1 = np.array([9, 8, 7, 6])
a2 = np.array([1, 2, 3, 4])
a_added = a1 + a2   # adding (np.add - has more parameters for adding)
a_subtr = a1 - a2   # subtracting (np.subtract)
a_multi = a1 * a2   # multiplication (np.multiply)
a_divid = a1 / a2   # division (np.divide)

# Vectorization with np. vs Python loops)
# ELEMENT WISE MULTIPLICATION
a_multi = np.multiply(a1,a2)    # [9*1, 8*2, 7*3, 8*4]
a_multi = np.zeros(len(a1))
for i in range(len(a1)):
    a_multi[i] = a1[i] * a2[i]

# DOT PRODUCT
a_dot = np.dot(a1,a2)           # 9*1 + 8*2 + 7*3 + 6*4
a_dot = 0
for i in range(len(a1)):
    a_dot += a1[i] * a2[i]

# OUTER PRODUCT
a_outer = np.outer(a1,a2)       # [[9*1, 9*2, 9*3, 9*4], [8*1, 8*2 …], … ]
a_outer = np.zeros((len(a1),len(a2)))
for i in range(len(a1)):
    for j in range(len(a2)):
        a_outer[i,j] = a1[i] * a2[j]


In [23]:
print("a_added =", a_added);    print("a_subtr =", a_subtr);   print("a_multi =", a_multi); 
print("a_divid =", a_divid);    print("a_dot =", a_dot);       print("a_outer:\n", a_outer)

a_added = [10 10 10 10]
a_subtr = [8 6 4 2]
a_multi = [ 9. 16. 21. 24.]
a_divid = [9.         4.         2.33333333 1.5       ]
a_dot = 70
a_outer:
 [[ 9. 18. 27. 36.]
 [ 8. 16. 24. 32.]
 [ 7. 14. 21. 28.]
 [ 6. 12. 18. 24.]]


In [24]:
# Arithmetic operations with matrix and vector (multiplication and dot product)
a1 = np.array([1, 2, 3, 4])
A1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])

Aa_multi = np.multiply(A1, a1)  # [[1*1, 2*2, 3*3, 4*4], [1*5, 1*6, 1*7, 1*8]]
Aa_dot = np.dot(A1, a1)         # [1*1 + 2*2 + 3*3 + 4*4, 5*1 + 6*2 + 7*3 + 8*4]
Aa_dot = np.zeros(A1.shape[0])
for i in range(len(A1)):
    for j in range(len(a1)):
        Aa_dot[i] += A1[i,j] * a1[j]

# Arithmetic operations with matrices (multiplication and dot product)
A2 = np.array([[4, 6],
               [3, 5],
               [2, 4],
               [1, 3]])
A11_multi = np.multiply(A1, A2.T)   # we need to transpose A2 to match the array shapes 
                                    # [[1*4, 2*3, 3*2, 4*1], [5*6, 6*5, 7*4, 8*3]]
A12_dot = np.dot(A1, A2)            # multiplying AxB * BxC shaped matrices (4x3 * 3x1) 
                                    # [[1*4 + 2*3 + 3*2 + 4*1, 1*6 + 2*5 + 3*4 + 4*3],
                                    #  [5*4 + 6*3 + 7*2 + 8*1, 5*6 + 6*5 + 7*4 + 8*3]]

In [25]:
print("Aa_multi:\n", Aa_multi);     print("Aa_dot =", Aa_dot); 
print("A11_multi:\n", A11_multi);   print("A12_dot:\n", A12_dot)

Aa_multi:
 [[ 1  4  9 16]
 [ 5 12 21 32]]
Aa_dot = [30. 70.]
A11_multi:
 [[ 4  6  6  4]
 [30 30 28 24]]
A12_dot:
 [[ 20  40]
 [ 60 112]]


In [26]:
# np.dot alternatives: @ and np.matmul in which the differences are:
# 1: Multiplication by scalars is not allowed -> use *
# 2: Stacks of matrices are broadcast together as if the matrices were elements.
#    (acts differently when we're dealing with 3D or higher dim. matrices)
# difference between matmul and @: matmul has additional parameters and works with lists
# https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication
# https://mkang32.github.io/python/2020/08/30/numpy-matmul.html

# dot vs @ example. Dot uses [2, 4] vector with all vectors, whereas @ multiplies them only with the corresponding matrix
a_3D = np.array([[[2, 4],
                  [1, 2]],
                 [[4, 6],
                  [7, 8]]])
b_3D = np.array([[[2, 4],
                  [1, 2]],
                 [[4, 6],
                  [7, 8]]])
ab_dot = np.dot(a_3D, a_3D)   # [[[[2*2 + 4*1, 2*4 + 4*2], [2*4 + 4*7, 2*6 + 4*8]], [1*2 + 2*1, 1*4 + 2*2] ...
ab_at = a_3D @ a_3D           # [[[2*2 + 4*1, 2*4 + 4*2], [1*2 + 2*1, 1*4 + 2*2]], [4*4 + 6*7, 4*6 + 6*8], [7*4 + 8*7, 7*6 + 8*8]]


In [27]:
print("ab_dot:\n", ab_dot); print("ab_at:\n", ab_at)

ab_dot:
 [[[[  8  16]
   [ 36  44]]

  [[  4   8]
   [ 18  22]]]


 [[[ 14  28]
   [ 58  72]]

  [[ 22  44]
   [ 84 106]]]]
ab_at:
 [[[  8  16]
  [  4   8]]

 [[ 58  72]
  [ 84 106]]]


In [39]:
# Index referencing and slicing
a = np.arange(10)
b = a[:]        # access all elements
b = a[0]        # gets the 1. element from the vector
b = a[2]        # gets the 3. element from the vector
b = a[2:7:1]    # access 5 consecutive elements (start:stop:step)
b = a[2:7:2]    # access 3 elements separated by two 
b = a[3:]       # access all elements index 3 and above
b = a[:3]       # access all elements below index 3
b = a[1:-1]     # gets all elements except for the first and last one

A = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
row = A[0]        # gets 1. row from 2D matrix
val = A[2][1]     # gets number 8 from 2D matrix
val = A[2, 1]     # does the same

idx = [0, 2]        # saving vector as index reference in a variable
A_idxed = A[idx]    # gets first and last row from 2D matrix

A_sub = A[0:2]      # gets first two rows from 2D matrix
A_sub = A[:2]       # does the same
A_sub_rows = A[1:4] # gets last two rows
A_sub_cols = A[:, 1]# gets all rows' second element

B = np.array([[[1,2,3], [2,3,4]],
              [[2,3,4], [6,5,4]]])
B_sub_step = B[::, ::, ::2] # gets first and last element in the vectors

In [43]:
print("a[:]     = ", a[:]);     print("a[2]     = ", a[2]); print("a[2:7:1] = ", a[2:7:1]);  print("a[2:7:2] = ", a[2:7:2])
print("a[3:]    = ", a[3:]);    print("a[:3]    = ", a[:3]);print("a[1:9]   = ", a[1:9]);   print("a[1:-1]  = ", a[1:-1],)
print("A:\n", A);             print("A_row =", row);      print("A_val =", val);            print("A_sub:\n", A_sub)
print("A_sub_rows:\n", A_sub_rows); print("A_sub_cols =", A_sub_cols);   print("B_sub_step:\n", B_sub_step)

a[:]     =  [0 1 2 3 4 5 6 7 8 9]
a[2]     =  2
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[1:9]   =  [1 2 3 4 5 6 7 8]
a[1:-1]  =  [1 2 3 4 5 6 7 8]
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A_row = [1 2 3]
A_val = 8
A_sub:
 [[1 2 3]
 [4 5 6]]
A_sub_rows:
 [[4 5 6]
 [7 8 9]]
A_sub_cols = [2 5 8]
B_sub_step:
 [[[1 3]
  [2 4]]

 [[2 4]
  [6 4]]]


In [45]:
# TODO: (ADDED FROM ML SPEC. polish later, naming of vars, "="'s 
# vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


In [44]:
# Copying and Broadcasting (treating arrays with different shapes during arithmetic operations)
X1 = np.array([[2, 3, 4],
               [3, 5, 8],
               [9, 8, 0]])
X2 = np.copy(X1)
X2[:] = 1   # sets all values to 1

X3 = X2.copy()
X3[0] = 0   # sets all values in the first row to 0

X4 = X3 * 2 # multipling matrix with a scalar (Python list would just duplicate the values)

In [43]:
print("X1:\n", X1); print("X2:\n", X2); print("X3:\n", X3); print("X4:\n", X4)

X1:
 [[2 3 4]
 [3 5 8]
 [9 8 0]]
X2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
X3:
 [[0 0 0]
 [1 1 1]
 [1 1 1]]
X4:
 [[0 0 0]
 [2 2 2]
 [2 2 2]]


In [44]:
# Types and conversions
A1 = np.zeros((3, 3))

A2 = A1.copy()
A2 = A2.astype('bool')  # conversion into bool type

A3_idx = A2.copy()      # creating matrix for index reference
A3_idx[0, 2] = True
A3_idx[1][0] = True
A3_idx[2] = True

X1 = np.array([[0, 0, 0],
              [0, 0, 8],
              [0, 1, 2]])
X1[A3_idx] = 300    # broadcasting using fully sized matrix as index reference 

# Conditioned filtering
X2 = X1.copy()
zeros_idx = X2 == 0     # get all 0 values
X2[zeros_idx] = 10      # set them to 10

# NumPy arrays contain only one type of variables. If there are more, it will be converted into string.
# If there are numbers and there’s also bool value, it’s going to be changed into a number. 
# Conversion priorities: string > int > bool
X_dtype = X.dtype

In [45]:
print("A1:\n", A1); print("A2:\n", A2); print("A3_idx:\n", A3_idx)
print("X1:\n", X1); print("X2:\n", X2); print("X_dtype =", X_dtype)

A1:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
A2:
 [[False False False]
 [False False False]
 [False False False]]
A3_idx:
 [[False False  True]
 [ True False False]
 [ True  True  True]]
X1:
 [[  0   0 300]
 [300   0   8]
 [300 300 300]]
X2:
 [[ 10  10 300]
 [300  10   8]
 [300 300 300]]
X_dtype = int32


In [46]:
# Stacking
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])
v_stack = np.vstack((a1, a2))   # joins arrays vertically, with a1 on the top
h_stack = np.hstack((a1, a2))	# joins arrays horizontally, with a1 on the left

In [ ]:
# TODO
# hsplit - splits an array into several smaller arrays


# Solving linear systems
A = np.array([[-1, 3],
              [3, 2]])
b = np.array([7, 1])
x = np.linalg.solve(A, b)	# [-1. 2.]
d = np.linalg.det(A)        # -11
b_norm = np.linalg.norm(b)
# Eigen Vectors..!